"""
Geocode restaurant addresses for the Lenzie Who Lunches and Dinners project.

This script only updates the CSV with Latitude/Longitude values.
It does not build or export any map HTML files.
"""

import os
import time

import pandas as pd
import requests

# Use a Mapbox public token with geocoding permission.
MAPBOX_TOKEN = "pk.eyJ1Ijoic2xsZW56aWUiLCJhIjoiY21sdG13MjB3MDF5dTNlcHBqZGt0NGVvdSJ9.-DaMTxcKxtsIZSl9_S7wNg"

INPUT_PATH = os.path.join("data", "lenzieswholunchanddinner.csv")
OUTPUT_PATH = os.path.join("data", "lenzieswholunchanddinner_geocoded.csv")


def _short(text: str, limit: int = 160) -> str:
    text = (text or "").replace("\n", " ").strip()
    return text[:limit] + ("..." if len(text) > limit else "")


def geocode_address(address_string: str, token: str):
    """Return (latitude, longitude) for an address, or (None, None) if unavailable."""
    if not address_string or "P.O. Box" in address_string or "PO Box" in address_string:
        return None, None

    geocode_url = (
        "https://api.mapbox.com/search/geocode/v6/forward"
        f"?q={requests.utils.quote(address_string)}"
        "&limit=1"
        f"&access_token={token}"
    )

    try:
        response = requests.get(geocode_url, timeout=10)
        if response.status_code != 200:
            return None, None, response.status_code, _short(response.text)

        data = response.json()
        features = data.get("features", [])
        if features:
            lon, lat = features[0]["geometry"]["coordinates"]
            return lat, lon, 200, "ok"
    except requests.exceptions.RequestException:
        return None, None, None, "request-exception"

    return None, None, 200, "no-features"


def main():
    if MAPBOX_TOKEN == "PASTE_YOUR_MAPBOX_TOKEN_HERE":
        print("ERROR: Add your Mapbox token in MAPBOX_TOKEN before running.")
        return

    if not os.path.exists(INPUT_PATH):
        print(f"ERROR: Input file not found: {INPUT_PATH}")
        return

    print("=" * 60)
    print("  Lenzie Who Lunches and Dinners Geocoder")
    print("=" * 60)

    df = pd.read_csv(INPUT_PATH)
    print(f"Loaded {len(df)} restaurants from: {INPUT_PATH}")

    latitudes = []
    longitudes = []
    failed = 0
    forbidden_hits = 0
    sample_failures = []

    print("\nGeocoding addresses with Mapbox...")
    for i, row in df.iterrows():
        name = row.get("Name", f"Row {i + 1}")
        address = row.get("Address", "")

        print(f"  [{i + 1}/{len(df)}] {name[:45]}...")
        lat, lon, status, note = geocode_address(address, MAPBOX_TOKEN)

        latitudes.append(lat)
        longitudes.append(lon)

        if not (lat is not None and lon is not None):
            failed += 1
            if status == 403:
                forbidden_hits += 1
            if len(sample_failures) < 5:
                sample_failures.append((name, status, note))

        time.sleep(0.1)

    df["Latitude"] = latitudes
    df["Longitude"] = longitudes

    os.makedirs("data", exist_ok=True)
    df.to_csv(OUTPUT_PATH, index=False, encoding="utf-8-sig")

    geocoded_count = df["Latitude"].notna().sum()

    print("\n" + "=" * 60)
    print("  SCRIPT COMPLETE")
    print("=" * 60)
    print(f"Geocoded rows: {geocoded_count}/{len(df)}")
    print(f"Failed rows: {failed}/{len(df)}")
    if sample_failures:
        print("Sample failures:")
        for name, status, note in sample_failures:
            print(f"  - {name}: status={status}, detail={note}")
    if forbidden_hits:
        print("\nDetected 403 Forbidden responses from Mapbox.")
        print("This usually means the token does not have Geocoding API access, or URL restrictions are blocking requests.")
        print("Update MAPBOX_TOKEN with a token that has geocoding permissions, then re-run.")
    print(f"Saved: {OUTPUT_PATH}")
    print("No map files were generated by this script.")


if __name__ == "__main__":
    main()
